### ISSUE TITLE
Retrieve the MAC address of the active interface

### ISSUE THREAD

**Issue by silvioprog** [repnop/mac_address#12]
Hi.

Is there any option to use `get_mac_address()` and retrieve the MAC address of the active interface?

Thank you!

**Comment by repnop** [comment]
Hi, sorry for the almost month long delay! Could you refine what you mean by "active interface"? Do you want the first interface which is marked as `UP` (at least on *nix, I'll have to do some digging on this for Windows)? There can be multiple interfaces, each which can be active by being the designated interface for certain routes.

**Comment by repnop** [comment]
closing as stale
