### ISSUE TITLE
Get network interface name for MAC address

### ISSUE THREAD

**Issue by ashaduri** [repnop/mac_address#14]
Since there is a way to get MAC address by name, a reverse should be possible - get name by MAC address (or embed the name into MacAddress struct). Example names would be "Wi-Fi" (Windows), "Local Area Connection" (Windows), "eth0" (Linux).

**Comment by repnop** [comment]
Hi, yeah this seems like a good idea but will probably require a partial (or maybe even full since I think I want to restructure other parts as well) rewrite of some stuff, so it might be a little bit. Sorry for the late reply! I'll see if I can carve some time out to do this soon :)
