### ISSUE TITLE
Support for serde?

### ISSUE THREAD

**Issue by gabrik** [repnop/mac_address#16]
Hi,

First, thank you for this useful crate.

I was wondering if there is any plan in adding support for [serde](https://github.com/serde-rs/serde) in order to serialize and deserialize the MAC addresses.

I had a quick look at the code and should suffice to add the derive for `Serialize` and `Deserialize` to `MacAddress`

Something like this:

```
extern crate serde;
...
use serde::{Serialize,Deserialize};

....
/// Contains the individual bytes of the MAC address.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct MacAddress {
    bytes: [u8; 6],
}

...
```

Thanks!

**Comment by repnop** [comment]
`serde` support has been added with `1.1.0` which I just published :) let me know if you run into any issues! I'm not covering the usecase for deserializing `[u8; 6]` directly since that's pretty trivial to do yourself, but it will deserialize from and into string values

**Comment by gabrik** [comment]
Awesome, thank you!
I will test it!
