### ISSUE TITLE
[Feature Request] Derive Eq, Hash for MacAddress

### ISSUE THREAD

**Issue by JackLiar** [repnop/mac_address#23]
Like the title saids, It would be convenient to derive Eq, Hash for MacAddress out of box, otherwise users have to create a wrapper struct to do this.

**Comment by repnop** [comment]
I didn't realize I forgot to include those, so thanks for making the issue! I think I should have some time to look this weekend and get a new version published out.

**Comment by repnop** [comment]
Fixed with v1.1.2 :)

**Comment by JackLiar** [comment]
Thx dude :)
