### ISSUE TITLE
Nl trait

### ISSUE THREAD

**Issue by AiyionPrime** [repnop/mac_address#25]
I'm not too deep into rust yet, but thought it might be possible to have an optional feature, that implements the [Nl trait of neli](https://docs.rs/neli/0.5.3/neli/trait.Nl.html)?
The two crates appear to have overlapping use-cases.

**Comment by repnop** [comment]
Hi, thanks for the issue! I'm absolutely open to having features for interop, however, I've never heard of `netlink` nor `neli` before this and from the small bit of reading I've done, its unclear to me what the purpose is -- would you mind expanding on how you think my crate fits in with it and what you mean by "The two crates appear to have overlapping use-cases"?

**Comment by AiyionPrime** [comment]
Netlink allows userspace programs to talk to kernel modules.
There are not many potent netlink crates in rust; neli being one of few good ones.

Often such kernel interaction is needed to modify routing tables, interfaces, ...
which all tend to have mac adresses in some of their attributes.

Maybe I'm wrong about this, but it might be nice to able to get mac-addresses out of generic netlink message-attributes.

**Comment by repnop** [comment]
Oh, if its mainly around de/serializing for the type, then sure I'd accept that as an optional feature flag :) do you have any examples where I could see what it would be like so I can make sure I properly implement it when I get time? Or, if you'd like, I'd also accept a PR if you feel doing it yourself.

**Comment by repnop** [comment]
closing as stale
