### ISSUE TITLE
Get MAC of the first adapter when multiple adapters are available on Windows

### ISSUE THREAD

**Issue by jetli** [repnop/mac_address#39]
I have an VPN on my Windows machine, the lib returns the mac address of the VPN, not the mac of the default adapter.  so do we need to loop in reverse order to get the mac of default adapter? or how can we get the en0 address?

![2801690877940_ pic](https://github.com/repnop/mac_address/assets/1142758/58121498-e57f-49e4-b8da-50b3057b9203)

**Comment by capveg-netdebug** [comment]
Btw - check out #42 - that allows you to pick the mac address by IP address.  Hopefully it can get approved soon.

**Comment by repnop** [comment]
you should be able to fetch the right adapter using [`get_mac_address_by_name`](https://docs.rs/mac_address/latest/mac_address/fn.mac_address_by_name.html) if you have a consistent name for the network adapter. if/when #42 gets merged, that will be another option as well.
