### ISSUE TITLE
Mac address changes after reboot (Raspberry Pi Zero W)

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [repnop/mac_address#44]
Each time I reboot my Raspberry Pi Zero W and get the mac address using `get_mac_adderss()` the address changes.

**Comment by repnop** [comment]
This crate doesn't control what MAC address the NIC(s) on your machine report as their MAC address, you may want to check that you don't have any kind of MAC address randomization or anything enabled, or if you have multiple NICs, you may be seeing it alternate between the two. Not really anything I'm able to do about this, so closing the issue.
